parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: VideoRental
    database_user: root
    database_password: '123'
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: c72cdbed888aa1eeec3a4565d1cf3191
    database_path: null
