app:
    resource: @AppBundle/Controller/
#    type:     yml

home:
    path: /home
    defaults: { _controller: AppBundle:Default:index }

test:
    path: /test
    defaults: { _controller: AppBundle:Default:test }

json:
    path: /json
    defaults: { _controller: AppBundle:Default:json }

app_video:
    resource: "@AppBundle/Resources/config/routing/video.yml"
    prefix:   /video

app_user:
    resource: "@AppBundle/Resources/config/routing/user.yml"
    prefix:   /user

app_feature:
    resource: "@AppBundle/Resources/config/routing/feature.yml"
    prefix:   /features

login_route:
    path:     /login
    defaults: { _controller: AppBundle:Security:login }

login_check:
    path: /login_check

log_out:
    path: /logout