user:
    path:     /
    defaults: { _controller: "AppBundle:User:index" }

user_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:User:show" }

user_new:
    path:     /new
    defaults: { _controller: "AppBundle:User:new" }

user_create:
    path:     /create
    defaults: { _controller: "AppBundle:User:create" }
    requirements: { _method: post }

user_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:User:edit" }

user_update:
    path:     /{id}/update
    defaults: { _controller: "AppBundle:User:update" }
    requirements: { _method: post|put }

user_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:User:delete" }
    requirements: { _method: post|delete }

#custom route
user_add_rental:
    path:     /{id}/add_rental
    defaults: { _controller: "AppBundle:Rentals:userAddRental" }
user_edit_rental:
    path:     /{id}/edit_rental/{rental_id}
    defaults: { _controller: "AppBundle:Rentals:userEditRental" }
user_archive_rental:
    path:     /{id}/archive_video/{rental_id}
    defaults: { _controller: "AppBundle:Rentals:userArchiveRental" }

role_add:
    path:     /add_role
    defaults: { _controller: "AppBundle:Default:addRole" }