AppBundle\Entity\User:
    type: entity
    table: users
    manyToMany:
        videos:
            targetEntity: Video
            mappedBy: users
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        firstname:
            type: string
            length: 25
        lastname:
            type: string
            length: 25
        username:
            type: string
            length: 25
            unique: true
        password:
            type: string
            length: 64
        email:
            type: string
            length: 60
            unique: true

        # don't forget to init the collection in the __construct() method of the entity