AppBundle\Entity\Video:

    type: entity
    oneToMany:
      videoId: # targets field
        targetEntity: UserVideos
        mappedBy: id

    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        title:
            type: string
            length: 25
        certificate:
            type: string
            length: 10
        director:
            type: string
            length: 25