AppBundle\Entity\Video:
    type: entity
    table: videos
    manyToMany:
    #what table
        users:
        #name entity
            targetEntity: User
            #what's the inverse (onetomany)
            inversedBy: videos
            #it's going to add a column in this table name
            joinColumn:
                name: user_id
                referencedColumnName: id
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        title:
            type: string
            length: 25
        certificate:
            type: string
            length: 10
        director:
            type: string
            length: 25